name: Java Selenium CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest  # Using Linux for better performance

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: maven  # Cache dependencies for faster builds

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Remove Snap Firefox and Install Firefox from PPA
        run: |
          sudo apt update
          sudo snap remove firefox || true  # Remove Snap Firefox if it exists
          sudo apt purge snapd -y  # Remove Snap completely
          sudo rm -rf /var/cache/snapd/  # Clean Snap cache
          echo "Installing Firefox from Mozilla PPA..."
          sudo add-apt-repository -y ppa:mozillateam/ppa
          echo 'Package: *' | sudo tee /etc/apt/preferences.d/mozilla-firefox
          echo 'Pin: release o=LP-PPA-mozillateam' | sudo tee -a /etc/apt/preferences.d/mozilla-firefox
          echo 'Pin-Priority: 1001' | sudo tee -a /etc/apt/preferences.d/mozilla-firefox
          sudo apt update
          sudo apt install -y firefox
          firefox --version

      - name: Install GeckoDriver (Fixed Version)
        run: |
          sudo apt install -y jq  # Ensure jq is installed for JSON parsing
          GECKODRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r ".tag_name" | sed 's/^v//')  # Remove "v" prefix
          echo "Latest Geckodriver Version: $GECKODRIVER_VERSION"
          
          # Construct the correct URL
          GECKODRIVER_URL="https://github.com/mozilla/geckodriver/releases/download/v${GECKODRIVER_VERSION}/geckodriver-linux64.tar.gz"
          
          echo "Downloading Geckodriver from: $GECKODRIVER_URL"
          wget -q "$GECKODRIVER_URL" -O geckodriver-linux64.tar.gz || (echo "Download failed" && exit 1)

          tar -xzf geckodriver-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          geckodriver --version

      - name: Build with Maven
        run: mvn clean install

      - name: Run Selenium Tests
        run: mvn test
