name: CI Workflow

on:
  pull_request:
    branches:
      - main  # Adjust to your default branch if necessary

jobs:
  test:
    runs-on: ubuntu-latest  # Running on the latest Ubuntu VM

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up JDK 8 with the Temurin distribution (AdoptOpenJDK's new name)
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'  # Specify the version of JDK
          distribution: 'temurin'  # Use 'temurin' instead of 'adoptopenjdk'

      # 3. Install Maven (using ad-m/setup-maven)
      - name: Set up Maven
        uses: ad-m/setup-maven@v1
        with:
          maven-version: '3.8.1'  # Specify your Maven version here

      # 4. Install Firefox
      - name: Install Firefox
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox

      # 5. Install dependencies (Maven)
      - name: Install dependencies (Maven)
        run: mvn install

      # 6. Run TestNG tests using Maven
      - name: Run TestNG tests
        run: mvn test
