name: CI Workflow

on:
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest  # Running on the latest Ubuntu VM

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Java JDK
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8' 

      # 3. Install Firefox
      - name: Install Firefox
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox

      # 4. Set up Maven 
      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          maven-version: '3.5.1'  

      # 5. Install dependencies (Maven)
      - name: Install dependencies (Maven)
        run: mvn install

      # 6. Run TestNG tests using Maven
      - name: Run TestNG tests
        run: mvn test
