name: CI Workflow

on:
  pull_request:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js (adjust based on your stack)
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust based on your Node.js version

      - name: Install dependencies
        run: npm install  # Or `yarn install` depending on your package manager

      - name: Run tests
        run: npm test  # Adjust according to your testing framework or script

      - name: Clean up Firefox snap (if it's causing issues)
        run: |
          sudo apt-get purge -y firefox
          sudo apt-get autoremove -y

      - name: Update packages (and fix apt)
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y  # Optionally upgrade packages
